NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.reliefcamp.disaster.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.reliefcamp.disaster.com-cert.pem
    OrganizationalUnitIdentifier: peer
